/* Autogenerated on 2015-05-12/19:08:28 by LABCAR. Do not alter. */
#ifndef _LABCARTOP_H
#define _LABCARTOP_H

#include "mc_module_hardware.h"
#include "mc_module_batterymodel_hil.h"
#include "mc_module_canmodule.h"
#include "mc_module_osmonitoring.h"

/* definition of the class structure */
struct LabCarTop_Class
{
  ASDObjectHeader objectHeader;
  struct Module_Hardware_Obj *Module_Hardware_Ptr;
  struct Module_Batterymodel_HiL_Obj *Module_Batterymodel_HiL_Ptr;
  struct Module_CANModule_Obj *Module_CANModule_Ptr;
  struct Module_OSMonitoring_Obj *Module_OSMonitoring_Ptr;
};

/* definition of the class object structure */
struct LabCarTop_Obj
{
  ASDObjectHeader objectHeader;
};

extern ASDObject *initializeLabCarModel(void);

/* RTIO helper functions */
#define GET_TABLE_OBJ_PTR(aName) (CharTable1_Obj *)(Module_Hardware_ClassObj.MCWrapper_##aName##_Ptr)

#endif /* _LABCARTOP_H */

