/* Autogenerated on 2015-05-12/19:08:28 by LABCAR. Do not alter. */
#define bool LABCAR_bool
#include "mc_module_hardware.h"
#include "../a_targma.h"

/* external declarations */
extern uint32 hwcStructID;
extern uint32 hwcParaID;

/* class initialization */
void initClass_Module_Hardware(struct Module_Hardware_Class *self)
{

  /* Characteristics */
  self->MCWrapper_hwcStructID_Ptr =
    initInstance_scalarWrapper((uint32)&hwcStructID, sizeof(uint32), (uint32)ASD_PARAMETER);
  self->MCWrapper_hwcParaID_Ptr =
    initInstance_scalarWrapper((uint32)&hwcParaID, sizeof(uint32), (uint32)ASD_PARAMETER);

  /* Measures */
};

/* definition of the class header */
static ASDClassHeader Module_Hardware_ClassHeader =
  { 0, 0, 0, 2, (MethodList *)0, (MethodList *)0 };

/* definition and initialization of the class object */
struct Module_Hardware_Class Module_Hardware_ClassObj =
{
  {1, { &Module_Hardware_ClassHeader }},
  NULL, NULL
};

/* initialization */
struct Module_Hardware_Obj *initModel_Module_Hardware(void)
{
  struct Module_Hardware_Obj *model;

  /* level 1 class initialization */
  initClass_Module_Hardware(&Module_Hardware_ClassObj);
  /* level 1 object initialization */
  model = initInstance_Module_Hardware();
  return (model);
};

/* object instantiation */
struct Module_Hardware_Obj *initInstance_Module_Hardware(void)
{
  struct Module_Hardware_Obj *self;
  /* object instantiation / implicit memory allocation */
  CREATE_OBJECT(self, Module_Hardware);
  return (self);
};

