/* Autogenerated on 2015-05-12/19:08:28 by LABCAR. Do not alter. */
#define bool LABCAR_bool
#include "mc_module_batterymodel_hil.h"
#include "../a_targma.h"

#undef bool
#undef false
#undef true
#ifndef USE_RTMODEL
  #define USE_RTMODEL
#endif // USE_RTMODEL

#include "batterymodel_hil_lcrtmacros.h"
#include "batterymodel_hil.h"
#include "batterymodel_hil_types.h"
extern Parameters_Batterymodel_HiL Batterymodel_HiL_P;
extern BlockIO_Batterymodel_HiL Batterymodel_HiL_B;

/* class initialization */
void initClass_Module_Batterymodel_HiL(struct Module_Batterymodel_HiL_Class *self)
{

  /* Characteristics */
  self->MCWrapper_Batterymodel_HiL_P_ChargeSwitch_Value_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.ChargeSwitch_Value, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_ChargeCurrentA1_Value_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.ChargeCurrentA1_Value, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_ChargeCurrentA_Value_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.ChargeCurrentA_Value, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Constant1_Value_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_P.Constant1_Value, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Gain1_Gain_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Gain1_Gain, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Constant_Value_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Constant_Value, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_C_diff_Value_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.C_diff_Value, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Vektorize_Gain_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_P.Vektorize_Gain, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Vektorize_Gain_o_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_P.Vektorize_Gain_o, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_UnitDelay_X0_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.UnitDelay_X0, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_R_balance_Value_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_P.R_balance_Value, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_01_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_01_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_01_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_01_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_02_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_02_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_02_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_02_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_03_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_03_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_03_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_03_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_04_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_04_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_04_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_04_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_05_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_05_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_05_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_05_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_06_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_06_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_06_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_06_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_07_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_07_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_07_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_07_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_08_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_08_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_08_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_08_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_09_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_09_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_09_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_09_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_10_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_10_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_10_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_10_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_11_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_11_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_11_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_11_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_12_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_12_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bala_12_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bala_12_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Gain_Gain_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Gain_Gain, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_C_diffR_diff_Value_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.C_diffR_diff_Value, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_UnitDelay1_X0_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.UnitDelay1_X0, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Gain1_Gain_a_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Gain1_Gain_a, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_UnitDelay_X0_n_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.UnitDelay_X0_n, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_R_ctR_i_Value_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.R_ctR_i_Value, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_UnitDelay_X0_k_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.UnitDelay_X0_k, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Gain_Gain_e_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Gain_Gain_e, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_poles_soc_Value_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_P.poles_soc_Value, sizeof(real64),(uint32)5, (uint32)5, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Gain_Gain_f_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Gain_Gain_f, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Q_0_Gain_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_P.Q_0_Gain, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_DiscreteTimeIntegrator_gainval_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.DiscreteTimeIntegrator_gainval, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_DiscreteTimeIntegrator_IC_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.DiscreteTimeIntegrator_IC, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_InitSoC_Value_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_P.InitSoC_Value, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_u11_Gain_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.u11_Gain, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_charge_currentA_Gain_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.charge_currentA_Gain, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_charge_currentmA_Gain_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.charge_currentmA_Gain, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bat_mode_system_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bat_mode_system_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bat_mode_system_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bat_mode_system_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_current_system_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.current_system_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_current_system_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.current_system_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_current_systemA_Gain_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.current_systemA_Gain, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Cellno_Value_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Cellno_Value, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_SoC_Kalman_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.SoC_Kalman_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_SoC_Kalman_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.SoC_Kalman_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_bat_voltagemV_Gain_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.bat_voltagemV_Gain, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_voltage_system_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.voltage_system_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_voltage_system_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.voltage_system_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_voltage_systemmV_Gain_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.voltage_systemmV_Gain, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_voltage_systemV_Gain_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.voltage_systemV_Gain, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_InitAmbientTemperatureK_Value_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_P.InitAmbientTemperatureK_Value, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Mod_CAN_RS232_Value_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Mod_CAN_RS232_Value, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT01_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT01_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT01_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT01_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT02_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT02_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT02_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT02_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT03_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT03_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT03_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT03_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT04_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT04_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT04_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT04_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT05_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT05_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT05_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT05_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT06_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT06_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT06_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT06_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT07_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT07_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT07_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT07_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT08_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT08_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT08_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT08_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT09_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT09_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT09_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT09_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT10_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT10_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT10_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT10_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT11_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT11_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT11_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT11_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT12_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT12_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellT12_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellT12_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV01_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV01_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV01_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV01_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV02_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV02_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV02_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV02_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV03_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV03_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV03_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV03_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV04_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV04_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV04_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV04_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV05_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV05_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV05_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV05_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV06_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV06_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV06_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV06_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV07_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV07_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV07_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV07_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV08_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV08_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV08_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV08_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV09_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV09_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV09_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV09_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV10_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV10_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV10_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV10_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV11_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV11_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV11_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV11_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV12_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV12_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_CellV12_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.CellV12_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Error_CellNo_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Error_CellNo_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Error_CellNo_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Error_CellNo_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Error_Event_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Error_Event_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Error_Event_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Error_Event_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Error_Indication_P3_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Error_Indication_P3, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_Error_Indication_P4_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.Error_Indication_P4, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_P_SoC_Kalman__Gain_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_P.SoC_Kalman__Gain, sizeof(real32), (uint32)ASD_PARAMETER);

  /* Measures */
  self->MCWrapper_Batterymodel_HiL_B_FromWs_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.FromWs, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_ChargeCurrentA_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.ChargeCurrentA, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_ChargeCurrentA_l_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.ChargeCurrentA_l, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Gain1_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Gain1, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_SumofElements_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.SumofElements, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Divide_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.Divide, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Abs_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.Abs, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Vektorize_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Vektorize, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Vektorize_d_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Vektorize_d, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_UnitDelay_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.UnitDelay, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Divide_k_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Divide_k, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bala_01_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bala_01, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bala_02_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bala_02, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bala_03_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bala_03, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bala_04_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bala_04, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bala_05_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bala_05, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bala_06_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bala_06, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bala_07_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bala_07, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bala_08_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bala_08, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bala_09_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bala_09, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bala_10_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bala_10, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bala_11_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bala_11, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bala_12_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bala_12, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Product_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Product, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Add_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Add, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Product_d_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Product_d, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Gain_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Gain, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_UnitDelay1_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.UnitDelay1, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Product1_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Product1, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Gain1_g_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Gain1_g, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_UnitDelay_l_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.UnitDelay_l, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Add_o_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Add_o, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Product2_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Product2, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_UnitDelay_o_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.UnitDelay_o, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Gain_p_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Gain_p, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Add1_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Add1, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Gain_k_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Gain_k, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_SumofElements1_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.SumofElements1, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Q_0_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Q_0, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_DiscreteTimeIntegrator_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.DiscreteTimeIntegrator, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Add_d_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.Add_d, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_u11_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.u11, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_charge_currentA_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.charge_currentA, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_charge_currentmA_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.charge_currentmA, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bat_mode_system_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bat_mode_system, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_current_system_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.current_system, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_current_systemA_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.current_systemA, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_SumofElements_c_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.SumofElements_c, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_SoCModel__Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.SoCModel_, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_SoC_Kalman_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.SoC_Kalman, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_deltaSoC_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.deltaSoC, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_sum_bat_voltageV_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.sum_bat_voltageV, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bat_voltagemV_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bat_voltagemV, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_voltage_system_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.voltage_system, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_voltage_systemmV_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.voltage_systemmV, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_voltage_systemV_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.voltage_systemV, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellT01_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellT01, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellT02_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellT02, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellT03_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellT03, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellT04_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellT04, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellT05_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellT05, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellT06_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellT06, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellT07_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellT07, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellT08_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellT08, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellT09_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellT09, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellT10_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellT10, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellT11_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellT11, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellT12_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellT12, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellV01_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellV01, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellV02_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellV02, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellV03_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellV03, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellV04_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellV04, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellV05_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellV05, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellV06_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellV06, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellV07_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellV07, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellV08_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellV08, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellV09_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellV09, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellV10_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellV10, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellV11_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellV11, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_CellV12_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.CellV12, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Error_CellNo_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.Error_CellNo, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Error_Event_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.Error_Event, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_Error_Indication_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.Error_Indication, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_current_out_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.current_out, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_y_Ptr =
    initInstance_vectorWrapper((uint32)&Batterymodel_HiL_B.y, sizeof(real64),(uint32)12, (uint32)12, (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_bat_modus_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.bat_modus, sizeof(real64), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_DataTypeConversion_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.DataTypeConversion, sizeof(real32), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_SoC_Kalman__Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.SoC_Kalman_, sizeof(real32), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_DataTypeConversion_f_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.DataTypeConversion_f, sizeof(uint16), (uint32)ASD_PARAMETER);
  self->MCWrapper_Batterymodel_HiL_B_DataTypeConversion1_Ptr =
    initInstance_scalarWrapper((uint32)&Batterymodel_HiL_B.DataTypeConversion1, sizeof(uint16), (uint32)ASD_PARAMETER);
};

/* definition of the class header */
static ASDClassHeader Module_Batterymodel_HiL_ClassHeader =
  { 0, 0, 0, 212, (MethodList *)0, (MethodList *)0 };

/* definition and initialization of the class object */
struct Module_Batterymodel_HiL_Class Module_Batterymodel_HiL_ClassObj =
{
  {1, { &Module_Batterymodel_HiL_ClassHeader }},
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
  NULL, NULL
};

/* initialization */
struct Module_Batterymodel_HiL_Obj *initModel_Module_Batterymodel_HiL(void)
{
  struct Module_Batterymodel_HiL_Obj *model;

  /* level 1 class initialization */
  initClass_Module_Batterymodel_HiL(&Module_Batterymodel_HiL_ClassObj);
  /* level 1 object initialization */
  model = initInstance_Module_Batterymodel_HiL();
  return (model);
};

/* object instantiation */
struct Module_Batterymodel_HiL_Obj *initInstance_Module_Batterymodel_HiL(void)
{
  struct Module_Batterymodel_HiL_Obj *self;
  /* object instantiation / implicit memory allocation */
  CREATE_OBJECT(self, Module_Batterymodel_HiL);
  return (self);
};

