/* Autogenerated on 2015-05-12/19:08:28 by LABCAR. Do not alter. */
#ifndef _MC_MODULE_OSMONITORING_H
#define _MC_MODULE_OSMONITORING_H

#include "../a_basdef.h"
#include "../y_primit.h"
#include "rtpc_task_statistic.h"

/* extern declarations */
extern struct Module_OSMonitoring_Obj *initModel_Module_OSMonitoring(void);
extern struct Module_OSMonitoring_Class Module_OSMonitoring_ClassObj;
extern void initClass_Module_OSMonitoring(struct Module_OSMonitoring_Class *class);
extern struct Module_OSMonitoring_Obj *initInstance_Module_OSMonitoring(void);

/* definition of the class structure */
struct Module_OSMonitoring_Class
{
  ASDObjectHeader objectHeader;

  /* Variables */
};

/* definition of the class object structure */
struct Module_OSMonitoring_Obj
{
  ASDObjectHeader objectHeader;
};

#endif /* _MC_MODULE_OSMONITORING_H */

