/* Autogenerated on 2015-05-12/19:08:28 by LABCAR. Do not alter. */
#ifndef _MC_MODULE_HARDWARE_H
#define _MC_MODULE_HARDWARE_H

#include "../a_basdef.h"
#include "../y_primit.h"

/* extern declarations */
extern struct Module_Hardware_Obj *initModel_Module_Hardware(void);
extern struct Module_Hardware_Class Module_Hardware_ClassObj;
extern void initClass_Module_Hardware(struct Module_Hardware_Class *class);
extern struct Module_Hardware_Obj *initInstance_Module_Hardware(void);

/* definition of the class structure */
struct Module_Hardware_Class
{
  ASDObjectHeader objectHeader;

  /* Characteristics */
  scalarWrapper_Obj *MCWrapper_hwcStructID_Ptr;
  scalarWrapper_Obj *MCWrapper_hwcParaID_Ptr;

  /* Measures */
};

/* definition of the class object structure */
struct Module_Hardware_Obj
{
  ASDObjectHeader objectHeader;
};

#endif /* _MC_MODULE_HARDWARE_H */

