/* Autogenerated on 2015-05-12/19:08:28 by LABCAR. Do not alter. */
#define bool LABCAR_bool
#include "mc_module_osmonitoring.h"
#include "../a_targma.h"



/* class initialization */
void initClass_Module_OSMonitoring(struct Module_OSMonitoring_Class *self)
{

  /* Variables */
};

/* definition of the class header */
static ASDClassHeader Module_OSMonitoring_ClassHeader =
  { 0, 0, 0, 0, (MethodList *)0, (MethodList *)0 };

/* definition and initialization of the class object */
struct Module_OSMonitoring_Class Module_OSMonitoring_ClassObj =
{
  {1, { &Module_OSMonitoring_ClassHeader }},
};

/* initialization */
struct Module_OSMonitoring_Obj *initModel_Module_OSMonitoring(void)
{
  struct Module_OSMonitoring_Obj *model;

  /* level 1 class initialization */
  initClass_Module_OSMonitoring(&Module_OSMonitoring_ClassObj);
  /* level 1 object initialization */
  model = initInstance_Module_OSMonitoring();
  return (model);
};

/* object instantiation */
struct Module_OSMonitoring_Obj *initInstance_Module_OSMonitoring(void)
{
  struct Module_OSMonitoring_Obj *self;
  /* object instantiation / implicit memory allocation */
  CREATE_OBJECT(self, Module_OSMonitoring);
  return (self);
};

