# Autogenerated on 2015-05-12/19:07:39 by LABCAR. Do not alter. #

####################################################################
# generated include file for a mid-level makefile
#
# Generic part:
#   SUBDIRS
#
# Mandatory part:
#   SUBDIRS
#
# Expected variables on entry:
#   None
#
# Prerequisites: 
#   None
#
# 2004-08-02 -Fra-
####################################################################

SUBDIRS := \
	global \
	batterymodel_hil
