/***********************************************************
 * May/12/2015   19:08:27                                  *
 *                                                         *
 * This code was automatically generated by LABCAR-RTC V5.1*
 * Beware of changing the code manually!                   *
 ***********************************************************/


#define ES1130_INSTANCE_1

#ifndef _ES113X_H
#define _ES113X_H

#include <connect.h>
#include "labcartop.h"
#include "../rtio/global/rtio.h"
#include "../rtio/global/rtio.h"
#include "../rtio/global/comm_err.h"

extern void rrtio_synchron_init(int es1130_instance, char *taskname);
extern void rrtio_synchron_exit(int es1130_instance);
extern void rrtio_synchron_flush(int es1130_instance);
extern void rrtio_synchron_wait(int es1130_instance);


#endif
