/***********************************************************
 * May/12/2015   19:08:27                                  *
 *                                                         *
 * This code was automatically generated by LABCAR-RTC V5.1*
 * Beware of changing the code manually!                   *
 ***********************************************************/


#define ES1130_INSTANCE_1

#include "es113x_rt.h"


void Es113x_InitCode_Init_HWCF()
{
installVmeVectorTable(vmeVectorTable);
installCommErrMessages(commErrMessages);
installEtasBoardNames(etasBoardNames);
installUserBoardNames(userBoardNames);
installEtasAutoIdBoardNames(etasAutoIdBoardNames);
installEtasPseudoGeoAdrBoardNames(etasPseudoGeoAdrBoardNames);
setGPIO32();
vmeSetupInt(5, RWD_MODE);
VME_INT_ENABLE();
rrtio_synchron_init(0,"TaskDVEModel");
}

void Es113x_ExitCode_Exit_HWCL()
{
rrtio_synchron_exit(0);
}

void Es113x_SyncSendCode_TaskDVEModel_HWCF()
{
rrtio_synchron_flush(0);
}

void Es113x_SyncReceiveCode_TaskDVEModel_HWCF()
{
rrtio_synchron_wait(0);
}


